services:
  db:
    image: postgres:16
    container_name: boundaryai-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surveys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d surveys"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
